#!/usr/bin/env bash

set -e
export DEP_DIR=${DEP_DIR:-$HOME/src/mac}
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
cd $DEP_DIR
rm -rf asio* lz4* mbedtls* tap*
echo "******* ASIO"
$O3/core/deps/asio/build-asio
echo "******* MBEDTLS"
TARGET=mingw $O3/core/deps/mbedtls/build-mbedtls
echo "******* LZ4"
TARGET=mingw $O3/core/deps/lz4/build-lz4
echo "******* TAP"
$O3/core/deps/wintap/build-wintap

#echo "******* MINICRYPTO"
#$O3/core/scripts/mac/build-minicrypto
#echo "******* SNAPPY"
#$O3/core/scripts/mac/build-snappy
