#!/usr/bin/env bash

set -e
if [ -z "$O3" ]; then
    echo O3 var must point to ovpn3 tree ; exit 1
fi
if [ -z "$DEP_DIR" ]; then
    echo DEP_DIR var must point to ovpn3 dependency tree
    exit 1
fi
cd $DEP_DIR

rm -rf mbedtls

if [ "$BUILD_IOS" = "1" ]; then
    # for ios, build with minicrypto
    for target in ios ; do
	echo '***************' TARGET $target
	VERBOSE=1 TARGET=$target USE_MINICRYPTO=0 $O3/core/deps/mbedtls/build-mbedtls
	[ "$IOS_DBG_ONLY" = "1" ] && exit
    done
fi
if [ "$BUILD_IOS_SIM" = "1" ]; then
    # ios simulators
    for target in iossim iossim-dbg ; do
	echo '***************' TARGET $target
	VERBOSE=1 TARGET=$target $O3/core/deps/mbedtls/build-mbedtls
    done
fi

# osx
[ -z "$OSX_MINICRYPTO" ] && OSX_MINICRYPTO=0
[ -z "$OSX_SERVER" ] && OSX_SERVER=1
if [ "$BUILD_OSX" = "1" ]; then
    for target in osx osx-dbg ; do
        echo '***************' TARGET $target
        VERBOSE=1 TARGET=$target USE_MINICRYPTO=$OSX_MINICRYPTO MINICRYPTO_NO_AES=1 ENABLE_SERVER=$OSX_SERVER $O3/core/deps/mbedtls/build-mbedtls
    done
fi
exit 0
